name: create apt repository
description: Create and deploy an apt repository from a bunch of built deb files
author: Jochen Sprickerhof
branding:
  icon: 'package'
  color: 'green'
inputs:
  BRANCH:
    description: repository branch to push to
    required: true
  GITHUB_TOKEN:
    description: Set to deploy to a DEB_DISTRO-ROS_DISTRO branch in the same repo.
    required: false
    default: false
  SQUASH_HISTORY:
    description: If set to true, all previous commits on the target branch will be discarded.
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Create apt repository
      run: $GITHUB_ACTION_PATH/../repository.sh
      shell: sh
      env:
        BRANCH: ${{ inputs.BRANCH }}
    - name: Deploy
      if: ${{ inputs.GITHUB_TOKEN }}
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: ${{ inputs.BRANCH }}
        FOLDER: /home/runner/apt_repo
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SQUASH_HISTORY: ${{ inputs.SQUASH_HISTORY }}
